### PR TITLE
Feature v2

### PR DESCRIPTION
**Pull request by okv**
Most of changes are breaking:

- [x] Drop comma separated target migrations support
- [x] Drop progress bar helper, recommend related plugin instead
- [x] Drop callback migrator interface support (but keep support of adapters callback interface)
- [x] Drop nodejs < 10 support
- [x] Update code linter rules (after dropping support of old nodejs versions)
- [x] Update dependencies
- [x] Revise excess dependencies (like pEachSeries)
- [x] Replace default migration template with async/await
- [x] Update doc: async/await examples first
- [x] Update bin/east output messages (consistent quotes style, etc)
- [x] Add changelog
- [x] Add transpiled langauges support (`sourceDir` and related options, ts types declarations, ts migration templae)
- [x] Add es modules support for config, migrations, adapters, plugins
- [x] Add tests to load config in different formats (json, common js module, es module)
- [x] Resolve adapter/plugin path by it's shape to cwd related path, abs path or module name

### CODE REVIEW

**Comment by okv** [comment]
east@2.0.0-alpha.1 published to npm

**Comment by okv** [comment]
I've just released east@2.0.0-alpha.6 which is (from my point of view) pretty close to release 2.0.0. I'm going to check it in real projects and release in a few days.
@MikeDevice @Veetaha it would be great if you could to check it against your use cases, projects. I'd appreciate any feedback.

**Comment by MikeDevice** [comment]
I just have checked. Works fine.

**Comment by okv** [comment]
Great, thanks for checking it.

On June 10, 2020 12:41:59 AM GMT+03:00, Mikhail Vyrodov <notifications@github.com> wrote:
>I just have checked. Works fine.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/okv/east/pull/50#issuecomment-641597422

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by okv** [comment]
east@2.0.0 released to npm

**Pull request merged**
